#!/usr/bin/env python3
"""
FoodLang AI Environment Setup Script

This script helps set up environment variables for development and production.
It generates secure secrets and creates properly configured .env files.

Usage:
    python setup-env.py [--env development|production]
"""

import os
import sys
import argparse
import secrets
import bcrypt
import getpass
from pathlib import Path

def generate_jwt_secret(length: int = 64) -> str:
    """Generate a secure JWT secret key"""
    return secrets.token_urlsafe(length)

def generate_password_hash(password: str) -> str:
    """Generate bcrypt hash for password"""
    salt = bcrypt.gensalt(rounds=12)
    hashed = bcrypt.hashpw(password.encode('utf-8'), salt)
    return hashed.decode('utf-8')

def create_backend_env(env_type: str, config: dict):
    """Create backend .env file"""
    env_file = f"backend/.env" if env_type == "development" else f"backend/.env.production"
    
    content = f"""# ============================================================================
# FoodLang AI Backend {env_type.title()} Environment Configuration
# Generated by setup-env.py
# ============================================================================

# OpenAI Configuration
OPENAI_API_KEY={config['openai_api_key']}

# JWT Configuration
JWT_SECRET={config['jwt_secret']}

# Admin Credentials
ADMIN_USERNAME={config['admin_username']}
ADMIN_PASSWORD={config['admin_password']}

# API Configuration
API_HOST=0.0.0.0
API_PORT=8000

# CORS Configuration
CORS_ORIGINS={config['cors_origins']}

# Rate Limiting Configuration
RATE_LIMIT_REQUESTS={config['rate_limit_requests']}
RATE_LIMIT_WINDOW=3600
ADMIN_RATE_LIMIT_REQUESTS={config['admin_rate_limit_requests']}

# Security Configuration
ALLOWED_HOSTS={config['allowed_hosts']}

# Environment
NODE_ENV={env_type}
"""
    
    with open(env_file, 'w') as f:
        f.write(content)
    
    print(f"Created {env_file}")

def create_frontend_env(env_type: str, config: dict):
    """Create frontend .env file"""
    env_file = f".env.local" if env_type == "development" else f".env.production.local"
    
    content = f"""# ============================================================================
# FoodLang AI Frontend {env_type.title()} Environment Configuration
# Generated by setup-env.py
# ============================================================================

# API Configuration
NEXT_PUBLIC_API_URL={config['api_url']}

# App Configuration
NEXT_PUBLIC_APP_NAME=FoodLang AI
NEXT_PUBLIC_APP_DESCRIPTION=Arabic ↔ English Food Packaging Translator

# Analytics
NEXT_PUBLIC_VERCEL_ANALYTICS_ID={config.get('analytics_id', '')}

# Environment
NODE_ENV={env_type}
"""
    
    with open(env_file, 'w') as f:
        f.write(content)
    
    print(f"Created {env_file}")

def setup_development():
    """Set up development environment"""
    print("Setting up DEVELOPMENT environment")
    print("=" * 40)
    
    # Get OpenAI API key
    openai_key = input("Enter your OpenAI API key (required): ").strip()
    if not openai_key:
        print("OpenAI API key is required!")
        sys.exit(1)
    
    # Generate JWT secret
    jwt_secret = generate_jwt_secret()
    print(f"Generated JWT secret: {jwt_secret[:20]}...")
    
    # Simple admin credentials for development
    admin_username = input("Admin username (default: admin): ").strip() or "admin"
    admin_password = input("Admin password (default: admin123): ").strip() or "admin123"
    
    config = {
        'openai_api_key': openai_key,
        'jwt_secret': jwt_secret,
        'admin_username': admin_username,
        'admin_password': admin_password,
        'cors_origins': 'http://localhost:3000,http://127.0.0.1:3000',
        'rate_limit_requests': '1000',
        'admin_rate_limit_requests': '500',
        'allowed_hosts': '*',
        'api_url': 'http://localhost:8000'
    }
    
    create_backend_env('development', config)
    create_frontend_env('development', config)
    
    print("\nDevelopment environment setup complete!")
    print("You can now run:")
    print("- Backend: cd backend && python main.py")
    print("- Frontend: npm run dev")

def setup_production():
    """Set up production environment"""
    print("Setting up PRODUCTION environment")
    print("=" * 40)
    
    # Get OpenAI API key
    openai_key = input("Enter your OpenAI API key (required): ").strip()
    if not openai_key:
        print("OpenAI API key is required!")
        sys.exit(1)
    
    # Generate secure JWT secret
    jwt_secret = generate_jwt_secret()
    print(f"Generated secure JWT secret: {jwt_secret[:20]}...")
    
    # Secure admin credentials
    admin_username = input("Admin username (avoid 'admin'): ").strip()
    if not admin_username or admin_username == 'admin':
        print("Please use a secure admin username (not 'admin')")
        sys.exit(1)
    
    admin_password = getpass.getpass("Admin password (will be hashed): ")
    if len(admin_password) < 8:
        print("Password must be at least 8 characters long!")
        sys.exit(1)
    
    # Hash the password
    hashed_password = generate_password_hash(admin_password)
    print("Password hashed successfully")
    
    # Get domain configuration
    frontend_domain = input("Frontend domain (e.g., https://myapp.vercel.app): ").strip()
    backend_domain = input("Backend domain (e.g., https://myapp.railway.app): ").strip()
    
    if not frontend_domain or not backend_domain:
        print("Both frontend and backend domains are required!")
        sys.exit(1)
    
    # Analytics ID (optional)
    analytics_id = input("Vercel Analytics ID (optional): ").strip()
    
    config = {
        'openai_api_key': openai_key,
        'jwt_secret': jwt_secret,
        'admin_username': admin_username,
        'admin_password': hashed_password,
        'cors_origins': frontend_domain,
        'rate_limit_requests': '50',
        'admin_rate_limit_requests': '20',
        'allowed_hosts': backend_domain.replace('https://', '').replace('http://', ''),
        'api_url': backend_domain,
        'analytics_id': analytics_id
    }
    
    create_backend_env('production', config)
    create_frontend_env('production', config)
    
    print("\nProduction environment setup complete!")
    print("IMPORTANT: Keep these credentials secure and never commit them to version control!")

def main():
    """Main function"""
    parser = argparse.ArgumentParser(description='Set up FoodLang AI environment')
    parser.add_argument('--env', choices=['development', 'production'], 
                       default='development', help='Environment type')
    
    args = parser.parse_args()
    
    print("FoodLang AI Environment Setup")
    print("=" * 30)
    
    if args.env == 'development':
        setup_development()
    else:
        setup_production()

if __name__ == "__main__":
    main()